### ISSUE TITLE
--no-color ?

### ISSUE THREAD

**Issue by willstott101** [C-Lodder/time-grunt#4]
Thanks for updating this module!

I'm using this in my sublime text build and colour isn't supported in there.

I'm calling grunt with `--no-color` but it appears this module will still print the final summary with colors. Which is rather hard to read when it isn't supported by the shell...

**Comment by C-Lodder** [comment]
Hi @willstott101 

I'm a little confused. Your sublime text build doesn't support colours, yet the module is still printing the text with the colours?

**Comment by willstott101** [comment]
Yes... colors in CLIs are just a group of control characters.

![screenshot from 2019-02-07 13-53-46](https://user-images.githubusercontent.com/335152/52415808-f64fa880-2adf-11e9-8748-e640cfe3facf.png)

**Comment by C-Lodder** [comment]
Hmm odd.

Could you please try the original package: https://github.com/sindresorhus/time-grunt
and see if you have the same issue?

The original repo uses Chalk as opposed to Kleur for colours

**Comment by willstott101** [comment]
Nope, no issue with the original package.

Color codes are hidden when I use --no-color

**Comment by C-Lodder** [comment]
Ok thanks for reporting. I'll try and get a fix out in the next couple of hours

**Comment by C-Lodder** [comment]
@willstott101 Would you mind testing this? https://github.com/C-Lodder/time-grunt/pull/5

Copy and paste the code from the `index.js` into `YOUR_PROJECT/node_modules/@lodder/time-grunt/index.js`

**Comment by C-Lodder** [comment]
Added with: https://github.com/C-Lodder/time-grunt/pull/5
